package com.profitscanner.web

object WebConst {

    const val API_KEY = "XCV1XX716R7YTPJC"

    /**
     *
     */
    const val SERVER_URL = "https:/www.alphavantage.co/query?function={function}&outputsize={size}&symbol={ticker}&apikey={key}"
    const val SERVER_URL_DEMO = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=ET&apikey=XCV1XX716R7YTPJC"
    const val FUNCTION_DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED"
    const val FULL_SIZE = "full"
    const val COMPACT_SIZE = "compact"


}

val tickers = "A,AA,AABA,AAL,AAN,AAP,AAPL,AAXN,ABBV,ABG,ABMD,ABT,ACAD,ACIA,ACN," +
        "ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEIS,AES,AFL,AGCO,AGN,AIG,AIR,AIV,AIZ,AJG,AKAM,AKZM,ALB," +
        "ALGN,ALGT,ALK,ALL,ALLE,ALLK,ALNY,ALRM,ALSN,ALV,ALXN,AMAT,AMCX,AMD,AME,AMED,AMG,AMGN,AMN," +
        "AMP,AMT,AMWD,AMZN,AN,ANAB,ANDE,ANET,ANIK,ANSS,ANTM,AON,AOS,APA,APD,APEI,APH,APTV,APY,ARE," +
        "ARMK,ARNC,ARW,ARWR,ASGN,ASH,ASIX,ATGE,ATKR,ATRI,ATRO,ATUS,ATVI,AVAV,AVB,AVDR,AVGO,AVLR," +
        "AVNS,AVP,AVY,AWI,AWR,AXE,AXP,AXSM,AYI,AYX,AZO,AZPN,BA,BAC,BAH,BAND,BAST,BAX,BBBY,BBSI,BBT," +
        "BBY,BC,BCO,BDC,BDX,BEAT,BECN,BEN,BERY,BF.B,BFAM,BH,BHF,BHGE,BID,BIG,BIIB,BIO,BJRI,BK,BKI,BKNG," +
        "BLD,BLK,BLKB,BLL,BLUE,BMI,BMRN,BMW,BMY,BPMC,BR,BRK.B,BRKR,BSX,BURL,BWA,BXP,C,CACC,CAG,CAH,CALM," +
        "CARG,CARS,CASY,CAT,CB,CBM,CBPO,CBRE,CBRL,CBS,CCI,CCK,CCL,CDNS,CE,CELG,CENT,CENTA,CERN,CF,CFG," +
        "CGNX,CHD,CHDN,CHE,CHGG,CHK,CHRW,CHTR,CI,CIEN,CINF,CL,CLF,CLGX,CLH,CLR,CLX,CMA,CMCO,CMCSA,CME," +
        "CMG,CMI,CMS,CNC,CNK,CNP,CNXN,COF,COG,COHR,COLM,COO,COP,COST,COTY,COUP,CPB,CPRI,CPRT,CPS,CR,CREE," +
        "CRI,CRL,CRM,CRMT,CROX,CRS,CRUS,CRVL,CSCO,CSGP,CSL,CSWI,CTAS,CTB,CTL,CTSH,CTVA,CTXS,CVCO,CVET,CVGW," +
        "CVLT,CVS,CVX,CXO,CY,D,DAL,DBX,DD,DDS,DE,DECK,DFS,DG,DGX,DHI,DHR,DIOD,DIS,DISCA,DISCB,DISCK,DK,DKS," +
        "DLB,DLPH,DLR,DLTR,DLX,DNOW,DOCU,DORM,DOV,DOW,DRI,DRQ,DVA,DVN,DXC,DXCM,DY,EA,EBAY,EBS,ECA,ECL,ED,EEFT," +
        "EFX,EIX,EL,ELAN,EMN,EMR,ENDP,ENSG,ENTA,ENV,EOG,EPAM,EPAY,EPC,EQIX,EQT,ERIE,ES,ESS,ET,ETFC,ETN,ETRN," +
        "ETSY,EVH,EW,EXAS,EXC,EXEL,EXLS,EXP,EXPD,EXPE,EXR,EYE,F,FANG,FARO,FAST,FB,FBHS,FCN,FCX,FDS,FDX,FFIV,FGEN," +
        "FICO,FIS,FISV,FITB,FIVE,FIVN,FIZZ,FL,FLIR,FLOW,FLR,FLS,FLT,FMC,FND,FORR,FOX,FOXA,FOXF,FRPH,FSLR,FTI," +
        "FTNT,FTR,FTV,FUL,GBT,GBX,GCO,GCP,GD,GDDY,GDOT,GE,GEF,GH,GHC,GHDX,GILD,GIS,GL,GLW,GM,GMED,GMS,GNRC,GOOG," +
        "GOOGL,GOSS,GPC,GPI,GPN,GPS,GRA,GRMN,GRUB,GS,GSKY,GT,GTLS,GTX,GVA,GWR,GWRE,GWW,H,HA,HAE,HAIN,HAL,HAS,HBAN," +
        "HBI,HCA,HCCI,HCP,HCSG,HD,HDS,HEAR,HES,HFC,HGV,HIG,HII,HIIQ,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HQY,HRB,HRL,HSIC," +
        "HST,HSY,HUBG,HUBS,HUM,HURN,HXL,IAC,IART,IBM,IBP,ICE,ICUI,IDCC,IDXX,IFF,IIVI,ILMN,IMMU,INCY,INFO,INGN,INGR," +
        "INTC,INTU,IONS,IP,IPAR,IPG,IPGP,IQV,IR,IRBT,IRM,IRTC,ISRG,IT,ITRI,ITW,IVZ,JBHT,JBSS,JCI,JCOM,JEC,JEF,JELD," +
        "JKHY,JLL,JNJ,JNPR,JOUT,JPM,JWN,K,KALU,KCEL,KDP,KEX,KEY,KEYS,KFY,KHC,KIM,KLAC,KMB,KMI,KMT,KMX,KNX,KO,KR,KSU," +
        "KTB,KZTK,L,LAD,LB,LEA,LECO,LEG,LEGH,LEN,LEVI,LGIH,LGND,LH,LHCG,LHX,LII,LIN,LITE,LKQ,LLY,LM,LMT,LNT,LOGM," +
        "LOPE,LOW,LRCX,LTHM,LULU,LUV,LVS,LYB,LYFT,LYV,M,MA,MAA,MAC,MAN,MANH,MANT,MANU,MAR,MAS,MASI,MAT,MATX,MCD," +
        "MCHP,MCK,MCO,MCRI,MD,MDB,MDLZ,MDRX,MDSO,MDT,MEDP,MEI,MELI,MET,MGLN,MHK,MIDD,MINI,MKC,MKL,MKTX,MLHR,MLM," +
        "MMC,MMM,MMS,MMSI,MNK,MNST,MO,MOS,MOV,MPC,MRK,MRO,MRTX,MS,MSCI,MSFT,MSG,MSGN,MSI,MSM,MSTR,MTB,MTCH,MTD,MTH," +
        "MTN,MTRN,MTSC,MU,MUR,MXIM,MYGN,MYL,MYOK,MYRG,NANO,NAVI,NBIX,NBL,NDAQ,NDSN,NEE,NEM,NEOG,NEU,NEWR,NFLX,NGVT," +
        "NJR,NKE,NKTR,NLSN,NOC,NOV,NOW,NRG,NSC,NSIT,NSP,NTAP,NTGR,NTNX,NTRS,NTUS,NUE,NUS,NUVA,NVDA,NVR,NVTA,NWL,NWS," +
        "NWSA,NXST,O,OC,ODFL,OFIX,OI,OKE,OKTA,OLED,OLLI,OMC,OMCL,ON,ORCL,ORLY,OSIS,OSK,OXY,PAGS,PANW,PATK,PAYC,PBCT," +
        "PBF,PBH,PBI,PCAR,PCG,PCTY,PD,PDCO,PEG,PEGA,PEN,PEP,PETQ,PFE,PFG,PFGC,PFPT,PG,PGR,PH,HM,PII,PINC,PKG,PKI,PLAN," +
        "PLAY,PLCE,PLD,PLNT,PLXS,PM,PNC,PODD,POL,POOL,POWI,PPG,PPL,PRAH,PRGS,PRLB,PRSC,PRSP,PRU,PS,PSA,PSTG,PSX,PTC,PVH," +
        "PWR,PXD,PYPL,PZZA,QADA,QCOM,QDEL,QLYS,QRTEA,QRVO,QUOT,R,RACE,RAMP,RARE,RAVN,RCL,RE,REG,REGN,REX,REZI,RF,RGEN," +
        "RGR,RH,RHI,RIG,RJF,RL,RMD,RNG,ROCK,ROG,ROK,ROKU,ROL,ROLL,ROP,ROST,RP,RPM,RRC,RRGB,RS,RSG,RTN,RYN,RYTM,SAFM," +
        "SAGE,SAIA,SAIL,SAM,SAVE,SBGI,SBUX,SCCO,SCHW,SCSC,SEDG,SEE,SEIC,SERV,SFIX,SFM,SGEN,SHAK,SHW,SIG,SINA,SITE,SIVB," +
        "SJM,SKX,SLAB,SLB,SLG,SMAR,SMG,SMTC,SNA,SNAP,SNBR,SNPS,SNX,SO,SP,SPG,SPGI,SPLK,SPR,SPSC,SQ,SRCL,SRDX,SRE,SRPT," +
        "SSD,SSNC,SSTK,STLD,STRA,STT,STX,STZ,SWAV,SWCH,SWI,SWK,SWKS,SWN,SXI,SXT,SYF,SYK,SYKE,SYMC,SYNH,SYY,T,TAP,TCBI," +
        "TCRR,TDC,TDG,TDS,TDY,TECD,TEL,TENB,TER,TFX,TGNA,TGT,THO,THRM,TIF,TJX,TKR,TMHC,TMO,TNDM,TNET,TOL,TPH,TPIC,TPR," +
        "TPX,TREE,TREX,TRIP,TRMB,TROW,TRU,TRV,TSCO,TSLA,TSN,TTD,TTWO,TWLO,TWOU,TWTR,TXN,TXRH,TXT,TYL,UA,UAA,UAL,UBER," +
        "UDR,UFPI,UFS,UHS,UI,ULTA,UNF,UNH,UNM,UNP,UPS,URBN,URI,USB,USFD,USM,UTHR,UTX,V,VAR,VC,VEEV,VFC,VIAB,VICR,VLO," +
        "VMC,VMW,VNE,VNO,VPG,VREX,VRNT,VRSK,VRSN,VRTU,VRTV,VRTX,VTR,VZ,W,WAB,WAT,WBA,WBC,WCC,WCG,WDAY,WDC,WEC,WELL,WERN," +
        "WEX,WFC,WGO,WH,WHD,WHR,WING,WLH,WLK,WLTW,WM,WMB,WMT,WOR,WRK,WSM,WSO,WTS,WTTR,WU,WWD,WWE,WWW,WY,WYND,WYNN,XEC,XEL," +
        "XLNX,XOM,XPO,XRAY,XRX,XYL,Y,YELP,YUM,Z,ZBH,ZBRA,ZEN,ZG,ZION,ZM,ZS,ZTS,ZUO"